# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install global dependencies
        run: python -m pip install -U pip setuptools wheel

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Install dev deps
        run: pip install -r requirements-dev.txt

      - name: Install password_validator
        run: pip install .

      - name: Run lint
        run: pylint src

      - name: Run tests
        run: coverage run -m unittest discover -s tests -v

      - name: Generate coverage report
        run: coverage report && coverage xml -i

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v1
